unstable_features = true
max_width = 80
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
reorder_imports = true
reorder_modules = true
edition = "2018"
merge_derives = true
use_field_init_shorthand = true
binop_separator = "Front"
combine_control_expr = true
condense_wildcard_suffixes = false
enum_discrim_align_threshold = 25
fn_single_line = true
force_multiline_blocks = true
format_macro_matchers = true
format_strings = true
imports_indent = "Visual"
indent_style = "Block"
inline_attribute_width = 40
match_arm_blocks = false
match_block_trailing_comma = true
imports_granularity= "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 25
struct_lit_single_line = true
where_single_line = true
brace_style = "AlwaysNextLine"
